# Generated by Django 6.0 on 2026-03-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=20)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
